[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "roamgen3client"
authors = [{name = "Simon", email = "Simon.Pigot@csiro.au"}]
dynamic = ["version", "description"]
